### ISSUE TITLE
User can create an event that starts after it ends

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#12]
**Summary**
You can create an event that has a start date/time that is after its end date/time

**Severity**
Medium 

**To Reproduce**
1. Go to create a workshop 
2. Enter a start date/time that is after end date/time 
3. Submit

**Expected behavior**
Form would be blocked if start and end are not in logical order

**Screenshots / Stack trace**
<img width="1440" alt="screen shot 2018-12-05 at 8 13 52 pm" src="https://user-images.githubusercontent.com/44003045/49557313-e1cb1600-f8cc-11e8-99a0-12f09ec952e7.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
Preform some form validation on the inputs

**Comment by LunaBestPone** [comment]
Not reproducible on current build. Considered as fixed.
