### ISSUE TITLE
Creating an unfinished workshop does not throw an error or create an event

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#13]
**Summary**
If the user creates a workshop that does not fill all the required fields the user is still redirected 

**Severity**
Medium 

**To Reproduce**
1. Go to create a workshop
2. Fill in all the fields except one
3. Hit submit

**Expected behavior**
User would be notified when their inputs do not meet the requirements

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
Preform some form validation on the inputs and then notify user if something does not pass.

**Comment by LunaBestPone** [comment]
Fixed
