### ISSUE TITLE
Clicking the links with the page name at the top of the page goes nowhere

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#3]
**Summary**
For all the pages, above the page on the left hand side is the page name that can be clicked. Clicking anyone of these makes the rest of the page blank. The user then has to click the link again from the navbar to get the content back. 

**Severity**
Low

**Screenshots / Stack trace**
If applicable, add screenshots or stack trace to help explain your problem.

<img width="1440" alt="screen shot 2018-12-03 at 8 18 03 pm" src="https://user-images.githubusercontent.com/44003045/49414331-9d0e7600-f738-11e8-8193-8e34a504c598.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
Redirect these links to the appropriate page

**Comment by kvyuan** [comment]
Removed awkward clickable page names across all pages.
