### ISSUE TITLE
Clicking logout does not force the user of the page

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#4]
**Summary**
Logging out leaves you on your current page

**Describe the bug**
When the user presses logout they are not force pushed off the page allowing them to see restricted info while not being logged in. 

**Severity**
High

**Screenshots / Stack trace**
<img width="1440" alt="screen shot 2018-12-03 at 8 25 58 pm" src="https://user-images.githubusercontent.com/44003045/49414612-aa783000-f739-11e8-8efb-752aab4eabaf.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
When the user presses the logout button it should take them back to the home page to avoid having restricted data displayed on the screen when logged out.

**Comment by haoysh** [comment]
When clicked log out, now it safely directs the page to home page.
