### ISSUE TITLE
Registering event does not register it to the user

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#5]
**Summary**
Even after registering for an event it does not show up in my workshops

**Severity**
High

**To Reproduce**
1. Go to workshops
2. Click an event
3. Click register
4. Go to my workshops

**Expected behavior**
An event the user registered for shows up in my workshops

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
Ensure that either the user is actually registered and that their registered events are displayed when navigating to my workshops

**Comment by kvyuan** [comment]
Fixed component state update
