### ISSUE TITLE
Registering for an event twice continually takes learning credits

### ISSUE THREAD

**Issue by NathanKiraly** [LunaBestPone/talentExOP2#6]
**Summary**
If you click register on event more than once, it will continually take learning credits from you even though you have already registered for the events. 

**Severity**
Medium 

**To Reproduce**
1. Go to events
2. Register for an event
3. Go back to the event
4. Register again

**Expected behavior**
Only allow a user to register once

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Suggestion**
Check if the user has registered for an event before and do not allow them to register if they already have.

**Comment by kvyuan** [comment]
Solved by Sung Ho
