### ISSUE TITLE
"Sign up" click fails to alert user of application status

### ISSUE THREAD

**Issue by ShannonFeng** [LunaBestPone/talentExOP2#7]
**Summary**
Clicking "sign up" does not alert the user of sign up or application status.

**Describe the bug**
When creating an account, the application does not redirect the user to another page or alert the user that an account was created. This leads to confusion about what the status of the user account is. Was the account successfully created? Will the user be redirected? Was there an issue with creating the account?

**Severity**
Low

**To Reproduce**
Start application and click the "Sign up" tab. Enter a username, email, and password and click sign up.

**Desktop**
OS: Windows 10
Browser: Chrome

**Suggestion**
To improve user experience, we recommend creating an alert that pops up when the user clicks "sign up" that alerts the user of the application status. This alert may say something like "Account creation successful. Redirecting to home..." and it can be presented in a green box. Or the alert be in a red box and say "Unable to create account. Please try again."

**Comment by LunaBestPone** [comment]
Fixed. Now user will receive on success message every time sign up is successful and get redirected.
