### ISSUE TITLE
Clicking "My Workshops" when not logged in does change tab color of "login"

### ISSUE THREAD

**Issue by ShannonFeng** [LunaBestPone/talentExOP2#8]
**Summary**
Clicking "My Workshops" when _not_ logged in does not change the tab color of the "login" tab to blue.

**Describe the bug**
When the "My Workshops" tab is clicked and the user is not logged in, the application says to "Log in before viewing your workshops" and the URL changes to /login. However, the login tab does not change to blue, and the My Workshops tab remains highlighted blue. This can create a confusing user experience because it is not obvious whether the user needs to still navigate to the login tab themselves or if they were redirected already.

**Severity**
Low

**To Reproduce**
Start application and click the "My Workshops" tab while not logged into an account.

**Desktop**
OS: Windows 10
Browser: Chrome

**Suggestion**
Please change the color of the login tab to blue after the application alerts the user that they must login to view My Workshops.

**Comment by haoysh** [comment]
My workshops is no longer visible when not logged in
